"""car request

Revision ID: de0df7fac642
Revises: a6294a742de0
Create Date: 2024-12-07 17:39:07.666499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de0df7fac642'
down_revision = 'a6294a742de0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CarRequest',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('car_info', sa.String(), nullable=False),
    sa.Column('price', sa.String(), nullable=False),
    sa.Column('additional_details', sa.String(), nullable=False),
    sa.Column('datetime_of_request', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tg_id'], ['User.tg_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CarRequest')
    # ### end Alembic commands ###
