"""Added Car model

Revision ID: cd6c45535729
Revises: 6736d3a85d61
Create Date: 2024-11-12 19:06:04.572419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd6c45535729'
down_revision = '6736d3a85d61'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
