"""update user model && create car model

Revision ID: 6736d3a85d61
Revises: 74146e1d677c
Create Date: 2024-11-11 20:22:56.562962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6736d3a85d61'
down_revision = '74146e1d677c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('name', sa.String(length=50), nullable=False))
    op.add_column('User', sa.Column('phone_number', sa.String(length=13), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'phone_number')
    op.drop_column('User', 'name')
    # ### end Alembic commands ###
